### PR TITLE
add resources for html and design, add to contributors

### PR DESCRIPTION
**Pull request by linda-lai**

### CODE REVIEW

**Comment by luvuong-le** [comment]
@linda-lai Hey Linda, just wondering if you may have missed something, I didn't see any resources being added for html and design in your commit, if you could double check that'd be great! 😃

**Review by linda-lai — COMMENTED** [review]
made minor changes, unable to submit new pull requests

**Comment by linda-lai** [comment]
Hi @luvuong-le, sorry I checked my files and the changes I made last night don't seem to have gone through! I made some edits to practice using Git for Hacktoberfest but unfortunately I don't seem to have done a very good job...just made some more minor edits to try again. Hopefully something comes through on your end?

**Review by luvuong-le — APPROVED** [review]

**Comment by luvuong-le** [comment]
@linda-lai That's alright, it's good practice to get into the habit of using git 👍 I myself participated in the Hacktoberfest as well. Regardless of what happened to your changes last night, it was just a small mishap is all, nothing bad! Practice makes perfect as always. Thanks for contributing and adding your resources!

**Comment by linda-lai** [comment]
Thanks for the encouragement @luvuong-le, it's definitely been helpful to get more familiar with using Git collaboratively! Glad to see that take two seem to have worked too - when I have time, I'll try to add some more resources in as well now. Thanks! ☺️

**Pull request merged**
